version: '3.0'
services:
  mongodb:
    image: mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=1234"
    ports:
      - "27017:27017"
    volumes:
      - mondo-data:/data/db
  mongo-express:
    depends_on:
      - mongodb
    restart: always
    image: mongo-express
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=1234"
      - "ME_CONFIG_MONGODB_SERVER=mongodb"
      - "ME_CONFIG_BASICAUTH_USERNAME=elisheva"
      - "ME_CONFIG_BASICAUTH_PASSWORD=12345"
    ports:
      - "8081:8081"
  my-app:
    image: elishevamiler/my-app:1.0
    build: .
    depends_on:
      - mongodb
    restart: always
    environment:
      - "MONGO_SERVER=mongodb"
      - "MONGO_USER=root"
      - "MONGO_PASSWD=1234"
      - "MONGO_PORT=27017"
    ports:
      - "3000:3000"
volumes:
  mondo-data:
    driver: local